### PR TITLE
Basic structure setup for client/server

### PR DESCRIPTION
**Pull request by codewizard-dt**
Renamed the 'get-lit' folder that has React to 'client'
Created 'server' folder and installed basic dependencies
Installed `concurrently` in the root folder and set up a `npm run dev` function that runs the following commands:

- `npm run start` for client
- `nodemon server.js` for server (note: server.js is empty except for a console.log('hi')

### CODE REVIEW

**Review by calliebwill — DISMISSED** [review]
solid

**Review by TEkdahl92 — DISMISSED** [review]
approved

**Review by TEkdahl92 — DISMISSED** [review]
approved

**Review by calliebwill — DISMISSED** [review]
hiiii

**Review by TEkdahl92 — APPROVED** [review]
approved

**Pull request closed without merging**
